"""GitHub PR creation for SwarmPR.

Builds PR titles, bodies, and labels from pipeline state, and creates
PRs via the GitHub API using PyGithub. Handles draft status based on
the escalation decision.
"""

from swarmpr.orchestrator.state import PipelineState


class PRCreator:
    """Creates GitHub pull requests from completed pipeline state.

    Builds structured PR metadata (title, body, labels, draft status)
    from the pipeline results and creates the PR via the GitHub API.

    Attributes:
        token: GitHub personal access token or app token.
    """

    def __init__(self, token: str) -> None:
        """Initialize with a GitHub token.

        Args:
            token: GitHub authentication token.
        """
        self.token = token

    def build_title(self, state: PipelineState) -> str:
        """Generate a PR title from the task description.

        Keeps the title under 70 characters per GitHub best practices.

        Args:
            state: The completed pipeline state.

        Returns:
            A concise PR title string.
        """
        prefix = "[SwarmPR]"
        task = state.task_description
        max_task_len = 70 - len(prefix) - 1
        if len(task) > max_task_len:
            task = task[: max_task_len - 3] + "..."
        return f"{prefix} {task}"

    def build_body(self, state: PipelineState) -> str:
        """Generate a structured PR body from pipeline results.

        Includes sections for changes, risk assessment, test results,
        review verdict, and pipeline metrics.

        Args:
            state: The completed pipeline state.

        Returns:
            A markdown-formatted PR body string.
        """
        sections = []

        # Header.
        sections.append("## Changes\n")
        if state.plan:
            for f in state.plan.files:
                sections.append(
                    f"- **{f.change_type.value}** `{f.path}`: "
                    f"{f.description}"
                )
        sections.append("")

        # Risk assessment.
        sections.append("## Risk Assessment\n")
        if state.plan:
            sections.append(f"- **Risk Tier**: Tier {state.plan.risk_tier}")
            sections.append(
                f"- **Justification**: {state.plan.risk_justification}"
            )
        if state.review:
            sections.append(
                f"- **Risk Score**: {state.review.risk_score}/10"
            )
            sections.append(
                f"- **Escalation**: `{state.review.escalation_action}`"
            )
        sections.append("")

        # Test results.
        sections.append("## Test Results\n")
        if state.tests_passed is True:
            sections.append("Tests **passed**.")
        elif state.tests_passed is False:
            sections.append("Tests **failed**.")
        else:
            sections.append("Tests were not run.")
        if state.test_output:
            sections.append(f"\n```\n{state.test_output}\n```")
        sections.append("")

        # Review verdict.
        sections.append("## AI Review\n")
        if state.review:
            sections.append(f"**Verdict**: {state.review.summary}")
            if state.review.findings:
                sections.append("\n**Findings**:\n")
                for finding in state.review.findings:
                    sections.append(f"- {finding}")
            action = state.review.escalation_action
            if action == "block":
                sections.append(
                    "\n> **Human review required** — this PR is "
                    "created as a draft."
                )
            elif action == "flag":
                sections.append(
                    "\n> AI-reviewed. Human review recommended."
                )
            else:
                sections.append(
                    "\n> AI-approved. Auto-merge eligible."
                )
        sections.append("")

        # Metrics.
        sections.append("## Metrics\n")
        if state.agent_results:
            total_ms = sum(r.duration_ms for r in state.agent_results)
            total_tokens = sum(
                r.tokens_in + r.tokens_out for r in state.agent_results
            )
            sections.append(f"- **Total duration**: {total_ms}ms")
            sections.append(f"- **Total tokens**: {total_tokens}")
        sections.append("")

        # Footer.
        sections.append(
            "---\n*Generated by [SwarmPR]"
            "(https://github.com/jallanhall/swarmpr) — "
            "multi-agent PR pipeline*"
        )

        return "\n".join(sections)

    def get_labels(self, state: PipelineState) -> list[str]:
        """Determine PR labels based on pipeline results.

        Args:
            state: The completed pipeline state.

        Returns:
            A list of label strings for the PR.
        """
        labels = ["swarmpr"]

        if state.plan:
            tier = state.plan.risk_tier
            if tier == 3:
                labels.append("risk:high")
                labels.append("tier-3")
            elif tier == 2:
                labels.append("risk:medium")
                labels.append("tier-2")
            else:
                labels.append("risk:low")
                labels.append("tier-1")

        if state.review:
            labels.append(
                f"escalation:{state.review.escalation_action}"
            )

        if state.tests_passed is True:
            labels.append("tests:passing")
        elif state.tests_passed is False:
            labels.append("tests:failing")

        return labels

    def should_be_draft(self, state: PipelineState) -> bool:
        """Determine if the PR should be created as a draft.

        Blocked PRs and PRs with failing tests are created as drafts
        to prevent accidental merging.

        Args:
            state: The completed pipeline state.

        Returns:
            True if the PR should be a draft, False otherwise.
        """
        if state.review and state.review.escalation_action == "block":
            return True
        if state.tests_passed is False:
            return True
        return False

    def create_pr(
        self,
        repo_full_name: str,
        state: PipelineState,
        base_branch: str = "main",
    ) -> str:
        """Create a pull request on GitHub.

        Args:
            repo_full_name: The full repo name (e.g., 'owner/repo').
            state: The completed pipeline state.
            base_branch: The branch to merge into.

        Returns:
            The URL of the created pull request.
        """
        from github import Github

        gh = Github(self.token)
        repo = gh.get_repo(repo_full_name)

        title = self.build_title(state)
        body = self.build_body(state)
        draft = self.should_be_draft(state)

        pr = repo.create_pull(
            title=title,
            body=body,
            head=state.branch_name,
            base=base_branch,
            draft=draft,
        )

        # Apply labels (create if they don't exist).
        labels = self.get_labels(state)
        for label_name in labels:
            try:
                repo.get_label(label_name)
            except Exception:
                repo.create_label(
                    name=label_name, color="ededed"
                )
        pr.set_labels(*labels)

        return pr.html_url
